// CLI entry point. Two commands: `start` runs the full pipeline in the
// foreground (recorder loop + index orchestrator concurrently); `stop`
// signals a running start process via a PID file.
//
// V1 deliberately keeps the process model trivial: a single foreground
// process, a single PID file, no daemon, no service integration. The user
// keeps a terminal open while recording. Background daemonization is V2.

import * as fs from "node:fs/promises";
import * as path from "node:path";
import { loadConfig, type Config } from "./config.js";
import { createContentDispatcher } from "./content/orchestrator.js";
import { createIndexOrchestrator } from "./index-module/orchestrator.js";
import { createLogger } from "./logging.js";
import { createRecorder } from "./recorder/orchestrator.js";
import { ensureDir, pathExists, writeFileAtomic } from "./utils/fs.js";
import { contextReadmePath } from "./utils/paths.js";

const log = createLogger("cli");

const CONTEXT_README_TEMPLATE = `# Screen Memory Index

This directory is a navigable record of screen activity, organized so any LLM
agent can browse it like a codebase. There is no search engine — you read the
index, navigate to what you need, and pull full content on demand.

## Layout

\`\`\`
~/context/
├── README.md                    ← this file
├── 2026/                        ← year
│   └── 04/                      ← month
│       ├── map.txt              ← month overview: one line per day + today's full sessions
│       └── 09/                  ← day (DD)
│           ├── sessions.txt     ← all sessions for the day, one per line
│           ├── session-001/
│           │   ├── meta.json    ← session metadata
│           │   ├── deltas.txt   ← timestamped one-liners (the per-clip log)
│           │   └── content/     ← full evidence (OCR text + key frame images)
│           ├── session-002/
│           └── ...
\`\`\`

## How to browse (zoom-in flow)

1. **Start with \`map.txt\`** for the current month — scan the month at-a-glance
   and see today's full sessions in one place.
2. **Pick a day** — \`cat 2026/04/09/sessions.txt\` to see all the day's session
   lines.
3. **Drill into a session** — \`cat 2026/04/09/session-001/deltas.txt\` to read
   the per-clip delta log.
4. **Pull full evidence** — \`ls 2026/04/09/session-001/content/\` for OCR text
   snapshots (\`base-HH-MM.txt\`) and key frame images (\`frame-HH-MM.jpg\`).

## Conventions

- **Times** are local wall-clock, formatted \`HH:MM\`.
- **Session windows** are \`[HH:MM–HH:MM]\`.
- **Deltas** are one-liners in compressed natural language. Example:
  \`[09:15] added OAuth client_id + client_secret entries to config.yaml\`.
- **Sessions** group related activity. A 2-minute Slack check in the middle of
  an hour of coding creates a separate session for the Slack interlude — that's
  intentional, the system optimizes for navigability by activity, not by time.
- **\`.dedup/\`** directories inside each session's \`content/\` are internal
  bookkeeping for deduplication. Ignore them.

## Caveat

This index is generated by an LLM watching short video clips of the screen.
Treat it like an attentive but imperfect note-taker: relations and entities
are usually right, but specific quoted text should be verified against the
\`content/\` snapshots when accuracy matters.
`;

function pidFilePath(config: Config): string {
  return path.join(config.logDir, "screen-memory.pid");
}

async function writePidFile(config: Config): Promise<void> {
  await ensureDir(config.logDir);
  await writeFileAtomic(pidFilePath(config), String(process.pid));
}

async function removePidFile(config: Config): Promise<void> {
  try {
    await fs.unlink(pidFilePath(config));
  } catch {
    /* best effort */
  }
}

async function readPidFile(config: Config): Promise<number | null> {
  const filePath = pidFilePath(config);
  if (!(await pathExists(filePath))) return null;
  const text = await fs.readFile(filePath, "utf8");
  const pid = Number(text.trim());
  return Number.isFinite(pid) && pid > 0 ? pid : null;
}

async function seedContextReadme(config: Config): Promise<void> {
  await ensureDir(config.contextDir);
  const readmePath = contextReadmePath(config.contextDir);
  if (await pathExists(readmePath)) return;
  await writeFileAtomic(readmePath, CONTEXT_README_TEMPLATE);
}

async function commandStart(): Promise<void> {
  const config = loadConfig();

  // Refuse to start a second instance — there's no IPC and two recorders
  // would race on filenames.
  const existingPid = await readPidFile(config);
  if (existingPid && isProcessAlive(existingPid)) {
    console.error(
      `screen-memory is already running (pid ${existingPid}). Use 'screen-memory stop' first.`
    );
    process.exit(1);
  }

  await ensureDir(config.stagingDir);
  await ensureDir(config.contextDir);
  await ensureDir(config.logDir);
  await seedContextReadme(config);
  await writePidFile(config);

  const dispatcher = createContentDispatcher(config);
  const indexOrch = createIndexOrchestrator(config, {
    contentDispatcher: dispatcher,
  });
  const recorder = createRecorder(config);

  let stopping = false;
  const shutdown = (signal: NodeJS.Signals): void => {
    if (stopping) return;
    stopping = true;
    log.info("shutdown signal received", { signal });
    recorder.stop();
    indexOrch.stop();
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);

  log.info("screen-memory starting", {
    contextDir: config.contextDir,
    stagingDir: config.stagingDir,
  });

  // Run recorder and index orchestrator concurrently. They communicate via
  // the staging directory; neither awaits the other.
  try {
    await Promise.all([recorder.start(), indexOrch.start()]);
  } finally {
    await removePidFile(config);
  }

  log.info("screen-memory stopped");
}

async function commandStop(): Promise<void> {
  const config = loadConfig();
  const pid = await readPidFile(config);
  if (!pid) {
    console.error("screen-memory is not running (no pid file)");
    process.exit(1);
  }
  if (!isProcessAlive(pid)) {
    console.error(`stale pid file (pid ${pid} not running) — removing`);
    await removePidFile(config);
    process.exit(1);
  }
  try {
    process.kill(pid, "SIGINT");
    console.error(`sent SIGINT to pid ${pid}`);
  } catch (err) {
    console.error(`failed to signal pid ${pid}: ${(err as Error).message}`);
    process.exit(1);
  }
}

function isProcessAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

function printUsage(): void {
  console.error(`usage: screen-memory <command>

Commands:
  start    Start recording (foreground; runs until Ctrl+C or 'screen-memory stop')
  stop     Signal a running screen-memory process to shut down

Environment:
  FIREWORKS_API_KEY              required — your Fireworks API key
  SCREEN_MEMORY_CONTEXT_DIR      default ~/context
  SCREEN_MEMORY_STAGING_DIR      default ~/.screen-memory/staging
  SCREEN_MEMORY_LOG_DIR          default ~/.screen-memory/logs
  SCREEN_MEMORY_POLL_INTERVAL_MS default 30000
  SCREEN_MEMORY_IDLE_TIMEOUT_CLIPS default 5
  SCREEN_MEMORY_BACKLOG_CEILING  default 60
  FIREWORKS_VLM_MODEL            override the default VLM model id
  FIREWORKS_TEXT_MODEL           override the default text LLM model id
`);
}

async function main(): Promise<void> {
  const cmd = process.argv[2];
  switch (cmd) {
    case "start":
      await commandStart();
      return;
    case "stop":
      await commandStop();
      return;
    case undefined:
    case "-h":
    case "--help":
    case "help":
      printUsage();
      process.exit(cmd === undefined ? 1 : 0);
      return;
    default:
      console.error(`unknown command: ${cmd}`);
      printUsage();
      process.exit(1);
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.stack ?? err.message : err);
  process.exit(1);
});
