// CLI entry point. Two commands: `start` runs the full pipeline in the
// foreground (recorder loop + index orchestrator concurrently); `stop`
// signals a running start process via a PID file.
//
// V1 deliberately keeps the process model trivial: a single foreground
// process, a single PID file, no daemon, no service integration. The user
// keeps a terminal open while recording. Background daemonization is V2.

import * as fs from "node:fs/promises";
import * as path from "node:path";
import { loadConfig, type Config } from "./config.js";
import { createContentDispatcher } from "./content/orchestrator.js";
import { createIndexOrchestrator } from "./index-module/orchestrator.js";
import { createLogger } from "./logging.js";
import { createBacklogMonitor } from "./recorder/backlog-monitor.js";
import { createRecorder } from "./recorder/orchestrator.js";
import { ensureDir, listDir, pathExists, writeFileAtomic } from "./utils/fs.js";
import { contextReadmePath } from "./utils/paths.js";
import { parseStagingFilename } from "./utils/timestamps.js";

const log = createLogger("cli");

const CONTEXT_README_TEMPLATE = `# Screen Memory Index

This directory is a navigable record of screen activity, organized so any LLM
agent can browse it like a codebase. There is no search engine — you read the
index, navigate to what you need, and pull full content on demand.

## Layout

\`\`\`
~/context/
├── README.md                    ← this file
├── 2026/                        ← year
│   └── 04/                      ← month
│       ├── map.txt              ← month overview: one line per day + today's full sessions
│       └── 09/                  ← day (DD)
│           ├── sessions.txt     ← all sessions for the day, one per line
│           ├── session-001/
│           │   ├── meta.json    ← session metadata
│           │   ├── deltas.txt   ← timestamped one-liners (the per-clip log)
│           │   └── content/     ← full evidence (OCR text + key frame images)
│           ├── session-002/
│           └── ...
\`\`\`

## How to browse (zoom-in flow)

1. **Start with \`map.txt\`** for the current month — scan the month at-a-glance
   and see today's full sessions in one place.
2. **Pick a day** — \`cat 2026/04/09/sessions.txt\` to see all the day's session
   lines.
3. **Drill into a session** — \`cat 2026/04/09/session-001/deltas.txt\` to read
   the per-clip delta log.
4. **Pull full evidence** — \`ls 2026/04/09/session-001/content/\` for OCR text
   snapshots (\`base-HH-MM.txt\`) and key frame images (\`frame-HH-MM.jpg\`).

## Conventions

- **Times** are local wall-clock, formatted \`HH:MM\`.
- **Session windows** are \`[HH:MM–HH:MM]\`.
- **Deltas** are one-liners in compressed natural language. Example:
  \`[09:15] added OAuth client_id + client_secret entries to config.yaml\`.
- **Sessions** group related activity. A 2-minute Slack check in the middle of
  an hour of coding creates a separate session for the Slack interlude — that's
  intentional, the system optimizes for navigability by activity, not by time.
- **\`.dedup/\`** directories inside each session's \`content/\` are internal
  bookkeeping for deduplication. Ignore them.

## Caveat

This index is generated by an LLM watching short video clips of the screen.
Treat it like an attentive but imperfect note-taker: relations and entities
are usually right, but specific quoted text should be verified against the
\`content/\` snapshots when accuracy matters.
`;

function pidFilePath(config: Config): string {
  return path.join(config.logDir, "screen-memory.pid");
}

async function writePidFile(config: Config): Promise<void> {
  await ensureDir(config.logDir);
  await writeFileAtomic(pidFilePath(config), String(process.pid));
}

async function removePidFile(config: Config): Promise<void> {
  try {
    await fs.unlink(pidFilePath(config));
  } catch {
    /* best effort */
  }
}

async function readPidFile(config: Config): Promise<number | null> {
  const filePath = pidFilePath(config);
  if (!(await pathExists(filePath))) return null;
  const text = await fs.readFile(filePath, "utf8");
  const pid = Number(text.trim());
  return Number.isFinite(pid) && pid > 0 ? pid : null;
}

async function seedContextReadme(config: Config): Promise<void> {
  await ensureDir(config.contextDir);
  const readmePath = contextReadmePath(config.contextDir);
  if (await pathExists(readmePath)) return;
  await writeFileAtomic(readmePath, CONTEXT_README_TEMPLATE);
}

async function commandStart(): Promise<void> {
  const config = loadConfig();

  // Refuse to start a second instance — there's no IPC and two recorders
  // would race on filenames.
  const existingPid = await readPidFile(config);
  if (existingPid && isProcessAlive(existingPid)) {
    console.error(
      `screen-mem is already running (pid ${existingPid}). Use 'screen-mem stop' first.`
    );
    process.exit(1);
  }

  await ensureDir(config.stagingDir);
  await ensureDir(config.contextDir);
  await ensureDir(config.logDir);
  await seedContextReadme(config);
  await writePidFile(config);

  const dispatcher = createContentDispatcher(config);
  const indexOrch = createIndexOrchestrator(config, {
    contentDispatcher: dispatcher,
  });
  const recorder = createRecorder(config);

  let stopping = false;
  const shutdown = (signal: NodeJS.Signals): void => {
    if (stopping) return;
    stopping = true;
    log.info("shutdown signal received", { signal });
    recorder.stop();
    indexOrch.stop();
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);

  log.info("screen-mem starting", {
    contextDir: config.contextDir,
    stagingDir: config.stagingDir,
  });

  // Run recorder and index orchestrator concurrently. They communicate via
  // the staging directory; neither awaits the other.
  try {
    await Promise.all([recorder.start(), indexOrch.start()]);
  } finally {
    await removePidFile(config);
  }

  log.info("screen-mem stopped");
}

/**
 * Parse `--parallel N` (or `--parallel=N`) from a flag list. Returns 1 if
 * absent or invalid. The flag is process-subcommand-scoped — main()'s
 * dispatcher doesn't see flags, this is parsed locally.
 */
function parseParallelFlag(argv: string[]): number {
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a === "--parallel" && i + 1 < argv.length) {
      const n = Number(argv[i + 1]);
      return Number.isFinite(n) && n >= 1 ? Math.floor(n) : 1;
    }
    if (a.startsWith("--parallel=")) {
      const n = Number(a.slice("--parallel=".length));
      return Number.isFinite(n) && n >= 1 ? Math.floor(n) : 1;
    }
  }
  return 1;
}

async function commandProcess(): Promise<void> {
  const config = loadConfig();
  const parallel = parseParallelFlag(process.argv.slice(3));

  // Refuse to run if a `start` instance is alive — they'd race on the same
  // staging files. The user should `screen-mem stop` first.
  const existingPid = await readPidFile(config);
  if (existingPid && isProcessAlive(existingPid)) {
    console.error(
      `screen-mem start is running (pid ${existingPid}). Stop it first with 'screen-mem stop'.`
    );
    process.exit(1);
  }

  await ensureDir(config.stagingDir);
  await ensureDir(config.contextDir);
  await ensureDir(config.logDir);
  await seedContextReadme(config);

  if (parallel > 1) {
    log.info("parallel mode enabled", { parallel });
  }

  const dispatcher = createContentDispatcher(config);
  const indexOrch = createIndexOrchestrator(config, {
    contentDispatcher: dispatcher,
    parallel,
  });
  // Backlog monitor with no ceiling — only used here for its count() method.
  const backlog = createBacklogMonitor(
    config.stagingDir,
    Number.POSITIVE_INFINITY
  );

  let stopping = false;
  const shutdown = (signal: NodeJS.Signals): void => {
    if (stopping) return;
    stopping = true;
    log.info("shutdown signal received during process", { signal });
    indexOrch.stop();
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);

  log.info("processing existing staging items", {
    stagingDir: config.stagingDir,
  });

  // Sanity check before draining: warn loudly about any files in staging
  // that don't match the expected filename pattern. Otherwise the drain
  // loop would silently exit with "staging drained" even though the user
  // has dozens of files sitting there with non-matching names.
  const allFiles = await listDir(config.stagingDir);
  const ignored = allFiles.filter((f) => parseStagingFilename(f) === null);
  const matched = allFiles.length - ignored.length;
  if (ignored.length > 0) {
    log.warn(
      `${ignored.length} file(s) in staging will be ignored — they don't match 'clip-HH-MM.mp4' or 'idle-HH-MM'`,
      { examples: ignored.slice(0, 3) }
    );
  }
  if (matched === 0) {
    log.info(
      "no matching files in staging — nothing to process. Rename your clips to clip-HH-MM.mp4 (e.g. clip-09-00.mp4, clip-09-01.mp4, ...) and try again."
    );
    return;
  }

  // Drain loop. Each iteration: count → drainOnce → recount. Bail if no
  // progress for 2 consecutive iterations (means everything left is stuck
  // and `drainOnce`'s in-process retry counter has dead-lettered it, or it
  // hits a permanent error).
  let prevRemaining = -1;
  let stallIterations = 0;
  const MAX_STALLS = 2;
  while (!stopping) {
    const remaining = await backlog.count();
    if (remaining === 0) {
      log.info("staging drained");
      break;
    }
    log.info("draining", { remaining });
    try {
      await indexOrch.drainOnce();
    } catch (err) {
      log.error("drainOnce failed", { error: (err as Error).message });
    }
    const after = await backlog.count();
    if (after === 0) {
      log.info("staging drained");
      break;
    }
    if (after >= prevRemaining && prevRemaining !== -1) {
      stallIterations += 1;
      if (stallIterations >= MAX_STALLS) {
        log.warn("no progress in drain loop — giving up", { remaining: after });
        break;
      }
    } else {
      stallIterations = 0;
    }
    prevRemaining = after;
  }

  await indexOrch.finalize();
  log.info("process command done");
}

async function commandStop(): Promise<void> {
  const config = loadConfig();
  const pid = await readPidFile(config);
  if (!pid) {
    console.error("screen-mem is not running (no pid file)");
    process.exit(1);
  }
  if (!isProcessAlive(pid)) {
    console.error(`stale pid file (pid ${pid} not running) — removing`);
    await removePidFile(config);
    return;
  }

  // SIGCONT first in case the process was Ctrl+Z'd — a suspended process
  // can't handle SIGINT until it's resumed.
  try {
    process.kill(pid, "SIGCONT");
  } catch {
    /* best effort */
  }

  // Graceful → SIGTERM → SIGKILL escalation. Anyone running `stop` wants the
  // process gone; this guarantees it.
  if (await sendAndWait(pid, "SIGINT", 5_000)) {
    console.error(`pid ${pid} exited cleanly`);
    await removePidFile(config);
    return;
  }
  console.error(`pid ${pid} did not exit on SIGINT, escalating to SIGTERM`);
  if (await sendAndWait(pid, "SIGTERM", 3_000)) {
    console.error(`pid ${pid} exited on SIGTERM`);
    await removePidFile(config);
    return;
  }
  console.error(`pid ${pid} ignored SIGTERM, sending SIGKILL`);
  if (await sendAndWait(pid, "SIGKILL", 2_000)) {
    console.error(`pid ${pid} killed`);
    await removePidFile(config);
    return;
  }
  console.error(
    `failed to kill pid ${pid} — try 'kill -9 ${pid}' manually, then remove ${pidFilePath(config)}`
  );
  process.exit(1);
}

async function sendAndWait(
  pid: number,
  signal: NodeJS.Signals,
  timeoutMs: number
): Promise<boolean> {
  try {
    process.kill(pid, signal);
  } catch (err) {
    // ESRCH means the process is already gone, which is success for us
    if ((err as NodeJS.ErrnoException).code === "ESRCH") return true;
    return false;
  }
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    if (!isProcessAlive(pid)) return true;
    await new Promise((r) => setTimeout(r, 100));
  }
  return false;
}

function isProcessAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

function printUsage(): void {
  console.error(`usage: screen-mem <command>

Commands:
  start    Start recording (foreground; runs until Ctrl+C or 'screen-mem stop')
  stop     Signal a running screen-mem process to shut down
  process  Run the index pipeline against existing clips in staging, then exit.
           Drop pre-recorded clips into ~/.screen-memory/staging/ named
           'clip-HH-MM.mp4' (the HH-MM is the wall-clock time you want on
           the deltas) and run this to backfill or test without recording.
           Add '--parallel N' to issue N VLM calls concurrently (default 1).

Environment:
  FIREWORKS_API_KEY              required — your Fireworks API key
  SCREEN_MEMORY_CONTEXT_DIR      default ~/context
  SCREEN_MEMORY_STAGING_DIR      default ~/.screen-memory/staging
  SCREEN_MEMORY_LOG_DIR          default ~/.screen-memory/logs
  SCREEN_MEMORY_POLL_INTERVAL_MS default 30000
  SCREEN_MEMORY_IDLE_TIMEOUT_CLIPS default 5
  SCREEN_MEMORY_BACKLOG_CEILING  default 60
  SCREEN_MEMORY_CAPTURE_INPUT    override the ffmpeg capture input
                                 (e.g. '2:none' on macOS if your screen is at avfoundation index 2)
  FIREWORKS_VLM_MODEL            override the default VLM model id
  FIREWORKS_TEXT_MODEL           override the default text LLM model id
`);
}

async function main(): Promise<void> {
  const cmd = process.argv[2];
  switch (cmd) {
    case "start":
      await commandStart();
      return;
    case "stop":
      await commandStop();
      return;
    case "process":
      await commandProcess();
      return;
    case undefined:
    case "-h":
    case "--help":
    case "help":
      printUsage();
      process.exit(cmd === undefined ? 1 : 0);
      return;
    default:
      console.error(`unknown command: ${cmd}`);
      printUsage();
      process.exit(1);
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.stack ?? err.message : err);
  process.exit(1);
});
